### ISSUE TITLE
Result tabs reappear after being closed

### ISSUE THREAD

**Issue by jaygen** [agirbal/umongo#12]
OS: OS X 10.7 Lion
JMongoBrowser 1.0.2
MongoDB 1.8.1

Steps to reproduce:
1 Run a query
2 Close result tab
3 Run another query
4 Old (closed) result tabs appears again along with new one

**Comment by agirbal** [comment]
ok thanks I did not get that issue on linux, will need to test.

**Comment by agirbal** [comment]
actually it's same issue on linux, will be fixed soon
