### ISSUE TITLE
tool to read the oplog

### ISSUE THREAD

**Issue by agirbal** [agirbal/umongo#173]

**Comment by braloum** [comment]
Is there finally a tool to read oplog?
I try to get logs between to date with no success !

{
"ts":{
        "$gt":{ "$timestamp" : { "t" : 1388448000 , "i" : 0}}

```
    ,"$lt":{ "$timestamp" : { "t" : 1388534400 , "i" : 0}}
}
```

}

nor this one:
{
"ts.t":{
        "$gt":1388448000
        ,"$lt":1388534400
    }
}

**Comment by agirbal** [comment]
You can click on replset node and then go to tools/query oplog.
From there you can put the start / end timestamp.
For ex you can start with { ts: { $timestamp: { t: 0, i: 0 } } } with no end.
