### ISSUE TITLE
Impossible to use Right+Click + Set or Update when use after a Find One

### ISSUE THREAD

**Issue by braloum** [agirbal/umongo#180]
When using FindOne, the document is well shown on the right panel.
Inside the document, when using :+1: 
- Right+Click on a field, the Set option shows the error :"Cannot do in-place update on local data."
- Right+Click on the top of the document, the Update option shows the update window, the Ok button does not generate an error, but the update has not been done !!!

When using Find that works correctly !

**Comment by agirbal** [comment]
thanks for report, will fix!

**Comment by agirbal** [comment]
I will probably just remove findOne altogether. It doesnt provide anything that cant be done with find(), and is really just a helper that makes sense in the shell.
