### ISSUE TITLE
Help -> About does not properly display version on Linux

### ISSUE THREAD

**Issue by clayzermk1** [agirbal/umongo#181]
On UMongo 1.4.3 for Linux, Help -> About shows:
![umongo](https://f.cloud.github.com/assets/1075015/1309203/0f5ff7c0-31db-11e3-8ab6-e016cd7e2029.png)

Let me know if I can help further.

**Comment by agirbal** [comment]
thanks for report

**Comment by clayzermk1** [comment]
You got it, thanks for the great product!
