### ISSUE TITLE
Replica sets do not show all members in the tree

### ISSUE THREAD

**Issue by clayzermk1** [agirbal/umongo#182]
On UMongo 1.4.3 for Linux, I have a replica set with four members.

The "ReplSet" tree object and the details panel for ReplSet only lists the first three. One system is powered down (unavailable) but it shows up in the set. Running ReplSet -> Command -> Config/Status will show all four members in the result.

Let me know how I can help futher.

**Comment by agirbal** [comment]
thanks for report. Could you paste the replica set configuration?
That server is just down?

**Comment by clayzermk1** [comment]
I have sanitized the status and configs, if something looks funky name/IP wise, that's probably why :wink:.

Correct, it is down for maintenance (powered off and unplugged).

Config:

```
{
  "_id": "rs0",
  "members": [
    {
      "_id": 0,
      "host": "master.example.com:27017"
    },
    {
      "_id": 1,
      "host": "slave1.example.com:27017",
      "priority": 0.0
    },
    {
      "_id": 2,
      "host": "slave2.example.com:27017",
      "priority": 0.0
    },
    {
      "_id": 3,
      "host": "backup.example.com:27017",
      "priority": 0.0,
      "votes": 0
    }
  ],
  "version": 8
}
```

Status:

```
{
  "date": {
    "$date": "2013-10-10T19:56:17.000Z"
  },
  "members": [
    {
      "_id": 0,
      "health": 1.0,
      "name": "master.example.com:27017",
      "optime": {
        "$inc": 1,
        "$ts": 1381434578
      },
      "optimeDate": {
        "$date": "2013-10-10T19:49:38.000Z"
      },
      "self": true,
      "state": 1,
      "stateStr": "PRIMARY",
      "uptime": 4512161
    },
    {
      "_id": 1,
      "health": 1.0,
      "lastHeartbeat": {
        "$date": "2013-10-10T19:56:15.000Z"
      },
      "name": "slave1.example.com:27017",
      "optime": {
        "$inc": 1,
        "$ts": 1381434578
      },
      "optimeDate": {
        "$date": "2013-10-10T19:49:38.000Z"
      },
      "pingMs": 0,
      "state": 2,
      "stateStr": "SECONDARY",
      "uptime": 7545
    },
    {
      "_id": 2,
      "errmsg": "socket exception [CONNECT_ERROR] for slave2.example.com:27017",
      "health": 0.0,
      "lastHeartbeat": {
        "$date": "1970-01-01T00:00:00.000Z"
      },
      "name": "slave2.example.com:27017",
      "optime": {
        "$inc": 0,
        "$ts": 0
      },
      "optimeDate": {
        "$date": "1970-01-01T00:00:00.000Z"
      },
      "pingMs": 0,
      "state": 8,
      "stateStr": "(not reachable/healthy)",
      "uptime": 0
    },
    {
      "_id": 3,
      "health": 1.0,
      "lastHeartbeat": {
        "$date": "2013-10-10T19:56:16.000Z"
      },
      "name": "backup.example.com:27017",
      "optime": {
        "$inc": 1,
        "$ts": 1381434578
      },
      "optimeDate": {
        "$date": "2013-10-10T19:49:38.000Z"
      },
      "pingMs": 0,
      "state": 2,
      "stateStr": "SECONDARY",
      "uptime": 7545
    }
  ],
  "myState": 1,
  "ok": 1.0,
  "serverUsed": "master.example.com/255.255.255.255:27017",
  "set": "rs0"
}
```

**Comment by agirbal** [comment]
which one is the server not showing up?
The one with votes 0?
Maybe there is some kind of exception happening while building that tree.
If you start the app from the command line you should be able to see the exceptions.
Otherwise you can download an early build of 1.5 and turn on logging from preferences.
https://s3.amazonaws.com/edgytech/umongo-windows-all_1-5-0.zip
There is also osx and linux version in there.

**Comment by clayzermk1** [comment]
Yes, sorry, the server "backup.example.com" with 0 votes was not showing up.

The server has since been brought online. I shut down mongodb on the server (I realize this isn't the same as powering it down) and started umongo from the command line using the command in the shell script but the server shows up in the set.

I don't know what to say. I have a feeling this is going to be hard to duplicate :frowning:

Thoughts?

**Comment by agirbal** [comment]
Most likely umongo had an exception connecting to slave2.example.com:27017 and as a result skipped backup.example.com:27017 at the end.

It could come from either this not listing the address:
        List<ServerAddress> addrs = mongo.getServerAddressList();

Or this throwing an exception when creating ServerNode:
        serverMongo = new Mongo(serverAddress, opts);

In any case this code needs to be more robust...

**Comment by clayzermk1** [comment]
Thank you for your efforts and your work!

Please let me know if I can be of any further help with this issue.

**Comment by agirbal** [comment]
Added try/catch block, most likely was exception creating a MongoClient instance
