### ISSUE TITLE
numIterated=50 always set?

### ISSUE THREAD

**Issue by tayS** [agirbal/umongo#198]
Using umongo-1-4-3 for Linux, every find command I run lists "numIterated=50" in the parameters and doesn't list more than 50 results. I am new to mongodb and umongo so if this is a mongodb limitation I am unaware. Is there a way to allow more than 50 results at a time to be displayed?

**Comment by agirbal** [comment]
it is just that umongo only iterates through 50 results in the window by default. Your query could match millions on documents, so it is not possible to display them all right away. If you want to see more, just click on "result/get more" or "result/get all". The 50 values can be changed in the preferences. Thanks
