### ISSUE TITLE
"This application requires a JRE V 1.6.0" message on start (Win7 x64 Java 7)

### ISSUE THREAD

**Issue by MaggieLeber** [agirbal/umongo#214]
The version check appears to be in the .exe, because the .jar starts OK

**Comment by agirbal** [comment]
thanks for the report. Weird, the .exe is created with launch4j and the only setting that mentions 1.6 is for the minimum version:
<jre>
    <minVersion>1.6.0</minVersion>
...
Not sure how to fix this

**Comment by agirbal** [comment]
I've tried to start both 1.6.1 and 1.6.2 on a newer windows and I didnt see any warning..

**Comment by MaggieLeber** [comment]
Well, it happened to me on Win7 x64 with Java 7. I've since replaced that machine with a Win8.1 machine on Java 1.7.0_51, I don't recall any issue when I installed umongo.

**Comment by MaggieLeber** [comment]
I'm going to guess that it was a launch4j issue...especially after browsing their bug tracker. I note that Mincraft seems to have has a similar issue with launch4j.
