### ISSUE TITLE
Bad JSON verification

### ISSUE THREAD

**Issue by braloum** [agirbal/umongo#218]
In the Find box, the query input doesnt correctly check the JSON entered :
Wrong opened or closed braces } does'nt emit an error message !

and Umongo sends a response from I imagine from a small part of the query !!

**Comment by agirbal** [comment]
Thanks for the report.
Could you give me a sample bad JSON?
Is the box for JSON checking checked or unchecked? Does it make a difference?

**Comment by braloum** [comment]
Just a simple example:
{"_id":{{{{{
{"$oid":"50c5c5b0b8be290c1d00014b"}}

There is too much "{" and no errors detected !!
even with the checkbox checked !

**Comment by braloum** [comment]
Do you have the same problem?

**Comment by braloum** [comment]
Up

**Comment by agirbal** [comment]
Ok I tried to paste the following
{"_id":{{{{{{"$oid":"50c5c5b0b8be290c1d00014b"}}

And the JSON parser from the driver parsed it in a very strange way with a key "{{{{{"$oid"".
So Looks like there is a bug in the parser when '{' are back to back.
Will open a ticket for that.

In the meantime, fixing this by adding a check using the GSON parser.
