### ISSUE TITLE
When query doc contains two equals clauses, only the second is applied

### ISSUE THREAD

**Issue by MaggieLeber** [agirbal/umongo#226]
For example...
    {"owner.user":"maggie"}
...does what you would expect. and so does 
    {"owner.user":"mleber"}

But 
    {"owner.user":"maggie", "owner.user" : "mleber"}
returns the same result as
    {"owner.user":"mleber"}
...when it should be empty.

**Comment by agirbal** [comment]
Hi Maggie,
in JSON there should not be duplicated keys. In this case, the java driver parses the keys fine into a hashmap and the last one overwrites the previous key. The only fix to this, would be for the java driver to throw exception if a key is seen duplicated. Feel free to open Java driver ticket issues at http://jira.mongodb.org

**Comment by MaggieLeber** [comment]
Hmm. Point is well-taken.
