### ISSUE TITLE
Timeout/lag issues

### ISSUE THREAD

**Issue by JBaldachino** [agirbal/umongo#47]
First off, thank you for your work, JMongo is my favorite Windows admin UI for Mongo.  

Version 1.1 seems to lag out very badly when a query is run at times.  The issues seems the worse when you enter an "incorrect" query - e.g. if you query for {property:5} from documents with properties [4,7,12,3]  the application will not respond until the query returns from the server or you kill the operation server side (either via command line or another instance of JMongo).  

Lengthy queries also seem to cause substantial lag/non-responding issues.  

None of these issues occurred in prior versions.  Could this be a configuration problem?  (I have not changed any default configurations in either 1.05 or 1.1).

**Comment by agirbal** [comment]
thanks a lot for report.
Bug is due to a change in java driver that makes cursor.toString() a blocking call.
Releasing 1.1.1 right now
