### ISSUE TITLE
Error: "Message: can't call something"

### ISSUE THREAD

**Issue by cjroth** [agirbal/umongo#55]
I'm getting the following error upon trying to connect to MongoDB: http://twitpic.com/7wueou/full

It says "Message: can't call something"

and the further down in the error details it shows this:

"Caused by: java.io.IOException: couldn't connect to [Zombie/127.0.1.1:27017] bc:java.net.ConnectException: Connection refused"

This is peculiar. I know the port is correct and authentication is turned off. I'm able to access it just fine through RockMongo.

**Comment by agirbal** [comment]
did you figure out the issue? Is mongod running on the same localhost box?
There is nothing specific done by jmongobrowser.
You can test by connecting the shell to the same mongod.

**Comment by cjroth** [comment]
Nope I never did figure it out. mongod was running on the same box.

**Comment by justincy** [comment]
I'm getting the same error. I'm running Ubunto 10.04.

**Comment by agirbal** [comment]
Are you running everything on your local box?
can you give the output of "$ ps aux | grep mongod"?
what is the host you give in the connect dialog of browser?
thx

**Comment by justincy** [comment]
Originally I was entering `localhost:27017` but I noticed that it was being translated to `127.0.1.1:27017`. So I tried entering `127.0.0.1:27017` instead and it worked.
