### ISSUE TITLE
Result sets: Overview lines should use full tab window width / Expand all nodes option

### ISSUE THREAD

**Issue by bogn** [agirbal/umongo#60]
First of all JMongoBrowser is a really nice tool, my first impression was that it's the best I found so far on Linux.

I really like the oneline per record overview in result sets. But currently they are truncated after let's say 70 to 100 characters. I'm quite sure people find it more useful to have them span the whole tab window width. If somebody want's less information there he can limit fields or is able to give the tab window less width.

Another nice addition would be an option to expand/collapse all record nodes.

**Comment by agirbal** [comment]
note that you can set the length you want in preferences.
Yes it would be good to automate the length.
Expand all will be easy to add.

**Comment by bogn** [comment]
Ah good to know, I looked at the preferences but assumed that setting to be for something else. In this case I'd say that "expand/collapse all" functionality has a higher priority.

If some day I will need a Java stack again (of course good choice for cross platform) I'd possibly jump in and add some features like a server list or colored keys in the result set or something like that.
