### ISSUE TITLE
UMongo "com.mongodb.MongoException: can't find a master" when try to connect

### ISSUE THREAD

**Issue by ftrotter** [agirbal/umongo#80]
As per the information here:
https://gist.github.com/3215681

All you need to do to fix this error is replace the word "localhost" with 127.0.0.1 to get this to work.

But basically this means that the DNS configuration of umongo is not considering the /etc/hosts file, which clearly maps "localhost" to 127.0.0.1

Despite the workaround this is still a bug.

-FT

**Comment by agirbal** [comment]
this was fix with driver upgrade
