### ISSUE TITLE
Linux startup instructions don't work at all

### ISSUE THREAD

**Issue by dbabits** [agirbal/umongo#81]
1) launch-umongo.sh refers to a file umongo.jar
The file is actually called mongo.jar

2)I edited it accordingly, got:
Failed to load Main-Class manifest attribute from agirbal-umongo-09a5bba/lib/mongo.jar

**Comment by clayzermk1** [comment]
This appears to be fixed as of version 1.2.1.

Worked out of the box for me on Debian 6 i686 and 7b4 x86_64.
I use Oracle java for both.
On 7 it is version:

```
java version "1.6.0_38"
Java(TM) SE Runtime Environment (build 1.6.0_38-b05)
Java HotSpot(TM) 64-Bit Server VM (build 20.13-b02, mixed mode)
```

**Comment by agirbal** [comment]
thanks for the report, sounds like it's fixed

**Comment by dbabits** [comment]
You must be kidding.
Just downloaded the latest version from git

1)$./package/linux/launch-umongo.sh
Unable to access jarfile umongo.jar

2)Checked, and AGAIN, the file is called mongo.jar

3)renamed it, still not able to launch.
$java -Xms64 -Xmx512 -jar mongo.jar
Error occurred during initialization of VM
Too small initial heap

$java -jar mongo.jar
Failed to load Main-Class manifest attribute from
mongo.jar

4)rm -rf umongo/

**Comment by agirbal** [comment]
thanks for report.
will release new version this week.

**Comment by clayzermk1** [comment]
@dbabits I think we are going about this different ways. I don't think the `mongo.jar` file you are referring to is umongo, but the mongodb library itself.

According to the readme:

```
** Download **

All binaries are available from:
- http://www.edgytech.com/umongo
```

I just downloaded the latest 1.4.2 linux zip and followed the instructions in the readme.
I extracted the zip and ran `launch-umongo.sh` - no problemo. `umongo.jar` is in the zip file.

I have not tried compiling the project with netbeans as the readme indicates.

What method of installation are you using? I believe the git repo is just a source repo without binaries since the binaries appear to be hosted separately on the Amazon cloud.

**Comment by dbabits** [comment]
@clayzermk1,
Thanks for your reply.

1)I downloaded from git, not from amazonws which is blocked for me at work.
Still, I think git should be the golden copy.

If you look at this file in github, you will see it refers to -jar umongo.jar:
https://github.com/agirbal/umongo/blob/master/package/linux/launch-umongo.sh

If you look at lib directory, you will see the file is called mongo.jar:
https://github.com/agirbal/umongo/tree/master/lib

Anyway, moving on..let me try and compile it myself..

2) downloaded latest ant from Apache: http://ant.apache.org/bindownload.cgi
$~/bin/apache-ant-1.9.2/bin/ant
Buildfile: build.xml

BUILD FAILED
/tmp/umongo/nbproject/build-impl.xml:23: Please build using Ant 1.8.0 or higher.

$~/bin/apache-ant-1.9.2/bin/ant -version
Apache Ant version 1.7.1 compiled on April 26 2010

???

This is where I have to give up again. Apache ant 1.9 is reporting an incorrect version, while you require 1.8, and Apache archive site is blocked to me, so I can't get an older version.

My suggestion is you  make git archive contain binaries as well.

Thank you.

**Comment by agirbal** [comment]
the binaries are no longer available from git, where did you get the copy?
See they deprecated the download service: https://github.com/agirbal/umongo/downloads

You should get it from girbal.net/umongo version 1.4.2

**Comment by dbabits** [comment]
Thanks agirbal, but I cannot get it from girbal.net/umongo, my previous message explains why

**Comment by clayzermk1** [comment]
Regarding the `umongo.jar`, as you can see below, the binary distributions contain it in the root directory. The `lib/` directory contains library files, `mongo.jar` is the MongoDB Java driver. That is not a spelling error or mistake, you should not be renaming that file.

``` sh
$ unzip -l umongo-linux-all_1-4-2.zip 
Archive:  umongo-linux-all_1-4-2.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2013-06-06 10:53   umongo-linux-all_1-4-2/
      346  2013-06-06 10:53   umongo-linux-all_1-4-2/launch-umongo.sh
        0  2013-06-06 10:53   umongo-linux-all_1-4-2/lib/
   190418  2013-06-06 10:53   umongo-linux-all_1-4-2/lib/gson-2.2.4.jar
   417208  2013-06-06 10:53   umongo-linux-all_1-4-2/lib/mongo.jar
   671105  2013-06-06 10:53   umongo-linux-all_1-4-2/lib/SwingFast.jar
       54  2013-06-06 10:53   umongo-linux-all_1-4-2/logging.properties
     1801  2013-06-06 10:53   umongo-linux-all_1-4-2/README
   843872  2013-06-06 10:53   umongo-linux-all_1-4-2/umongo.jar
---------                     -------
  2124804                     9 files
```

To echo what @agirbal said about the download service, here is [the official memo](https://github.com/blog/1302-goodbye-uploads) and the [current suggestions for binary distribution](https://help.github.com/articles/distributing-large-binaries). It's basically frowned upon by Github (it's not a good idea to put binary files in Git if you can help it).

Regarding this issue: I think that it should be closed; the Linux startup instructions are straight-forward and work.

Regarding your build issues: Have you tried using netbeans as suggested by the README? Not to sound like a jerk, but I think if you have problems building you should open a new issue for that.

```
** Compile **

Right now, you can only compile the app using the netbeans project, which should be improved soon.
```

Other thoughts: I presume you'd just like to get a copy of the binary distribution. You should just ask @agirbal, now that you have his attention, if he would be willing to send you a copy via some other means for the time being. (I would do so myself, but there isn't a LICENSE associated with the project, nor is one mentioned on the binary page or in the README. So I don't know if that's ok.)

**Comment by dbabits** [comment]
thanks. tried using netbeans, it didn't work.
@agirbal, If possible, post the download somewhere in code.google.com

Thank you.

**Comment by sffranke** [comment]
Funny, since 2013 still wrong instructions for Linux.....

**Comment by dbabits** [comment]
Hello, nice to see this  message from the time machine. Hope everybody is doing fine :)

**Comment by sffranke** [comment]
Yes thank you, greetings from sunny Germany, spring is coming soon, we are healthy, what else we need (except termination  the war in Ukraine)?
