### ISSUE TITLE
Feature Request: Save / Remember / Bookmark Mongo Instance connections

### ISSUE THREAD

**Issue by clayzermk1** [agirbal/umongo#85]
Maybe I'm just not searching for the right keywords. Is there some way to do this already?

I'd like a way for UMongo to remember the Mongo Instances I connect to.
Maybe a checkbox on the Connect Dialog and on the Mongo Instance Options Dialog?

Something like this:
File > Connect
Type in server info, check box to remember the connection, click Ok.
Server connects, I do stuff for a bit then close UMongo.
The next day, I open UMongo and all remembered connections automatically reconnect.

**Comment by olagache** [comment]
:+1:  for the connections manager but without the "automatically reconnect"  :)

**Comment by FullMontag** [comment]
:thumbsup: for this one
