### ISSUE TITLE
"unmongo" is damaged an can't be opened

### ISSUE THREAD

**Issue by alexbirkett** [agirbal/umongo#86]
Steps to reproduce on n OS X 10.8.2:

Download:
https://github.com/downloads/agirbal/umongo/umongo-osx-all_1-2-1.zip

Extract the zip

Right click and choose open on umongo
## Expected result

App opens
## Actual result

Message '"unmongo" is damaged an can't be opened' is displayed

**Comment by wuct** [comment]
+1

**Comment by gistya** [comment]
+1 I am having the same issue. Would really like to use this on Mac. I have the latest OS release.

**Comment by cecon** [comment]
not work on windows...
Error: Could no find main class: com.adgytech.umongo.UMongo

**Comment by agirbal** [comment]
thanks for the report.
It is working fine for me on 10.7.5.
Will try to correct that.

About windows, it would be surprising that it cannot find the class.
Make sure you read the instructions and click on the right app.
thanks

**Comment by agirbal** [comment]
I've tried on 10.8.2 also and it seems to work just fine.
Maybe try downloading again from the github link:
https://github.com/agirbal/umongo/downloads

**Comment by rchampourlier** [comment]
Same here. Tried both website download, GitHub download, and even the previous version 1.2.0, none works.

OS X 10.8.2

**Comment by a7medkamel** [comment]
+1 on OS X 10.8.2

**Comment by agirbal** [comment]
thanks for the report, I'll try to fix it asap.
In the meantime you should be able to look into the app folder and start umongo as a java application, either by double clicking the jar or calling java -jar from command line.

**Comment by prateekm21** [comment]
+1 OSX 10.8.2
![Screen Shot 2013-02-23 at 12 20 09 AM](https://f.cloud.github.com/assets/1644883/187799/cb7a2326-7d91-11e2-8d94-851fe3589683.png)

**Comment by agirbal** [comment]
Can you try a few things:
- go to "system preferences / security and privacy / General"
  Make sure that "allow applications downloaded from" is set to "anywhere".
- It could also be that you have a case-sensitive file system.
  Run "diskutil list /" from the command line and see if it says case-sensitive.

One workaround is to right-click on the file, select Show Package Contents, then go to Contents -> Resources -> Java. Then, just open using jar. You can make an alias to this for easy access if you want.

**Comment by agirbal** [comment]
As per above comment it should work
